### ISSUE TITLE
Allow for any decimal of Renown and Downtime

### ISSUE THREAD

**Issue by rexmaxus** [Ariel-Thomas/adventurers-league-log#219]
Depending on how games actually go it is possible to only get .25 (or even .125) of a Renown (1ACP earned but with slow progression). Please allow for these smaller decimals to be added. Currently only x.5 is able to be saved. Thank you.

**Comment by Brynnan42** [comment]
I was coming here to suggest this. Since hours played is always an integer and rounded down, AGP and TCP are always integers. Downtime is awarded in increments of 2.5 (not 1 and not 0.5) and currently supported by the system. Renown, however, is awarded in increments of 0.25 and is not supported fully by the system.

Adding the quarters (0.25 and 0.75) to Renown is badly needed for those that play hardcovers for an odd number of hours, and I would suggest limiting Downtime to increments of 2.5 instead of 0.5, but that's optional.

**Comment by Brynnan42** [comment]
Looking at the previous poster, I did not think about Slow Progression. so yes, additional entries to support that would be needed.

**Comment by Eleros** [comment]
^Thirding this request.

**Comment by Ariel-Thomas** [comment]
TODO

**Comment by Ariel-Thomas** [comment]
Done.
