### ISSUE TITLE
Sort by level

### ISSUE THREAD

**Issue by Carmcritter** [Ariel-Thomas/adventurers-league-log#249]
This app is great, but when trying to pick a character for a game being able to sort by level would be very helpful.

**Comment by derammo** [comment]
duplicate of #64

**Comment by Carmcritter** [comment]
Thanks. I don't have time to try and search for previous attempts for a simple fix. This has been brought up numerous times before even 11 months ago when that request was submitted.

**Comment by derammo** [comment]
Sorry for not proving more complete instructions.   That wasn't an attack, no need to defend yourself :)

I meant (and again sorry for not being explicit):  "Please close this as duplicate of #208.  The close issue button is found near the bottom of this issue as viewed on github.  I can't do it for you because I am just a user trying to help out to save Ariel's time."
