### ISSUE TITLE
Campaigns

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#4]
Would it be possible to create a Game or Session log for the DM?

There is a log for DM rewards this would be for the game or session itself

It wouod include:
- Date
- Location
- DM info
- Name
- DCI
- Character Info
- Player Name
- Character Name
- Class and Level
- DCI
- XP Awarded
- GP Awarded
- Downtime Awarded
- Renown Awarded
- Magic Item Awarded and Character who received it
- Notes
  
  An XML output option for
  - Single Character
  - All Characters
  - All DM logs
  - All Game logs
  - All User Data
  - DM Log Entries

Add a date used for the character assigned so that the DM awards are properly interlaced into the characters log sheet

**Comment by Ariel-Thomas** [comment]
Probably doable, and definitely a good idea, but kind of a narrow use-case

Also to consider: Does this mean it shows up for players but they can't alter the entry?

**Comment by brustmlj** [comment]
If the player selected a game to log and the DM had already entered the information I could populate with the ability to overwrite.  But mostly I see this as a DM tool.

**Comment by TheSheDM** [comment]
Not sure if this is related, but my DM logs don't show a date played anymore? Makes it confusing trying to figure out which event the DM log occurred at - important for tallying up events that occurred before or after a certain date.   
![20160823_102003](https://cloud.githubusercontent.com/assets/21070243/17902248/673bddfe-691b-11e6-91b1-05d49b6d18c8.png)

**Comment by Ariel-Thomas** [comment]
This issue hasn't been implemented yet. Changes that have already happened are labeled as closed. This is related to Issue #20 . I'm going to spin off another thread for this. 

Try to post these sorts of things as separate issues in the future, please. 

Thanks for the report.

**Comment by Ariel-Thomas** [comment]
Sorry, it's PR #20, Issue #8

**Comment by TheSheDM** [comment]
Sorry about that!

**Comment by Mahewa** [comment]
I was trying to experiment with the Campaigns feature, and think it's looking really good, but I seem to have broken it on my account.  To see how it would work I created a campaign and then joined that campaign as a player.  I tried to delete the campaign, and now I can't access the Campaigns part of the site at all.  I get the message: "We're sorry, but something went wrong."

But while I could use it I was really liking what I saw.  The only thing I could think of to make it more useful is the ability to assign magic items to specific characters, since I would think you'd apply the log to multiple characters, but they generally wouldn't all get each magic item.

**Comment by Ariel-Thomas** [comment]
Oh, shoot. So it's the player side that's breaks, then?

Right now my intention is that you'll just make a new log for magic item assignment. I'm not quite sure how to make magic item assignment work well in the context of the log system I currently have in place.

**Comment by Mahewa** [comment]
Sorry, I'm not sure what side I clicked delete on that broke it.  I thought I clicked it on the DM side, but I can't access that section at all anymore.

That makes sense.

Also, thanks so much for creating the site and putting all this effort into it.  I've found it very helpful.

**Comment by Ariel-Thomas** [comment]
I think I fixed the issue. See if you can access the campaign page again now.

**Comment by Mahewa** [comment]
It is working again, thanks.  Is it okay for me to make a new campaign and continue trying it out as both player and DM, or is that what broke it?

**Comment by Ariel-Thomas** [comment]
About to push up an update. After that it won't be an issue. The problem was that deleting a character or campaign breaks the other due to me not setting things up to destroy the association between the two.

**Comment by Ariel-Thomas** [comment]
I need to figure out a satisfactory way to handle magic items (from a programmatic standpoint) and I think this will be complete.

**Comment by taki021** [comment]
I am not sure if I am in the wrong section, but is it possible in the campaign to add player DCI number on the "show campaign" and "show log entry" ?

**Comment by Mahewa** [comment]
Sorry, I thought I'd asked this before, but I guess I forgot.  Is there any way you can delete the orphaned entry on my character sheet?  It's stuck there since I deleted the campaign before you applied the fix discussed earlier in the thread.  This is the link to the entry: http://www.adventurersleaguelog.com/users/429/characters/595/campaign_log_entries/7833

Let me know if there's other info that would be helpful.

**Comment by Ariel-Thomas** [comment]
I've deleted the orphaned entry.
