### ISSUE TITLE
Deleting DM Information

### ISSUE THREAD

**Issue by kenibrewer** [Ariel-Thomas/adventurers-league-log#55]
If you accidentally save a log sheet with incorrect DM information (name/DCI), it is impossible to later remove/correct that from the drop down menu of previous DMs.

**Comment by Ariel-Thomas** [comment]
Hm... I'm not sure where I'd put a button to manage DMs. Any suggestions?

**Comment by kenibrewer** [comment]
Perhaps instead of the "Manual Entry" checkbox over the DM dropdown you could put an "Add/Edit DMs" link. The trick would be to find a way that people can do that without losing whatever they've already entered in an adventure log.

**Comment by Ariel-Thomas** [comment]
I think I'll make it a dropdown after Change My Details.

**Comment by tjclayton** [comment]
In the DM drop down list you could just put an X to delete. It doesn't work for edit, but it keeps you in the same place. 

Either way, if you Delete a DM it should not remove the DM info from logs previously referencing that DM. The DM info should be written to that entry like when systems keep track of purchases. If the product is deleted it doesn't remove it from the sale transaction. 

The person can go back to the entry to change it.

**Comment by kenibrewer** [comment]
I much prefer than the dropdown after "Change My Details" to having delete "X"s inside a dropdown list. 

But I agree with tjclayton that deleting a DM from the list shouldn't remove his info from previous logs. That would actually make it a useful feature for those of us who go to conventions and play with lots of DMs we'll probably never see again.  

However, if you edit DM information, I think that would be good to have that automatically change past entries.

**Comment by tjclayton** [comment]
The only thing to keep in mind is that I personally hate having to go to other screens when you are in the middle of an entry screen. Oops, I forget to edit the DM details and now I have to start over again.

**Comment by Ariel-Thomas** [comment]
Yeah, if there's an alternate screen for DM management it would need to be a new tab, like what happens when you hit the print button.

**Comment by tjclayton** [comment]
I think having a link under "Change My Details" as a general DM management tool is fine (and it wouldn't need to open in a new tab just like Change My Details doesn't). The part I am commenting on is the workflow a person takes when in the middle of entering or updating a log entry (echoing kenibrewer's comment here https://github.com/Ariel-Thomas/adventurers-league-log/issues/55?_pjax=%23js-repo-pjax-container#issuecomment-274368352). 

Today I have a dropdown for an exiting entry or a checkbox to do a manual entry.What is the flow for when I've entered all my log information and realize that I haven't gamed with this DM before? Can I still manually enter it here? What is the flow at this point where I have the DM info in my dropdown, but I realize it is incorrect? Just add it and then go to the tool to update it after I save the entry?

In both of those scenarios I do not want to have to open a page in a new tab and make some change and then close that tab to come back and continue adding/updating the entry. Also, from a page development perspective, if you do that how will the dropdown be updated?

Personally, I think this involves two things:

1. A management interface like you are describing for just going and managing DM information. Maybe if the delete is too hard since it looks like there is a desire for edit to update previous sheets, then have a "hide" option instead that hides it from the dropdown, but then the information will still show on previously assigned sheets.

2. A control within the workflow of adding a log entry to minimally add new DM information and optimally to edit at that point if I see a mistake.

Print is a different workflow than this, I think, since it is not within the flow of adding/updating information.

From a simplicity perspective, the main issue is probably just solved by allowing things to be removed from the dropdown at this point since incorrect information in the dropdown is the main issue and don't worry about updating, linking, etc. However, if a more sophisticated solution is implemented, I'm not sure the workflow being discussed here is optimal.

**Comment by Ariel-Thomas** [comment]
Doneish. I'll look into adding a better inline option for DM management in the future.
