### ISSUE TITLE
Add optional link from character to an online character sheet

### ISSUE THREAD

**Issue by rooneg** [Ariel-Thomas/adventurers-league-log#60]
For people who maintain their character sheets online (mine are google spreadsheets) it would be nice if there was a way to include that link on the character page.

**Comment by Ariel-Thomas** [comment]
Will figure something out for this.

**Comment by Ariel-Thomas** [comment]
The design of this is kind of driving me nutty since I can't come up with anything good despire how simple it is. My hope is if I just do something I'll eventually make it better.

I thinking I may just add a button or link next/uner to the character name that shows up if you have an associated link for this.

**Comment by rooneg** [comment]
For what it's worth, a link/button next to the character name that shows up if you've added a link seems perfectly fine for me.
